sudo: false
language: node_js
node_js:
  - stable
  - '5'
  - '4'
  - '0.12'
  - '0.10'
matrix:
  fast_finish: true
  allow_failures:
    - node_js: '0.10'
before_install:
  - "git config --global user.name 'jonschlinkert'"
